name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: janet-lang/janet
        path: ./janet
        ref: refs/heads/master
    - name: make
      run: make
      working-directory: ./janet
    - name: make install
      run: make install
      working-directory: ./janet
    - name: jpm build
      run: jpm build
    - name: jpm test
      run: jpm test


